FROM node:11.7.0-alpine

RUN mkdir /etc/app
WORKDIR /etc/app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --loglevel error
RUN npm cache clean --force 

COPY . .

ENTRYPOINT [ "npm", "run", "start:dev" ]